information:
    client_name: ""
    server_name: ""
    rclone_connection_name: ""
    bucket_name: ""
    exclusion_file: "exclude-files"
    keep_daily: "90" # 90 days by default

binaries:
    restic: "/usr/bin/restic"

email:
    enable: false
    sender: "backups@local.dev"
    to: ""
    host: "127.0.0.1"
    port: "1025"
    max_try: "5"
    timeout: "60"
