#!/usr/bin/env python
import argparse
import re
import subprocess

import yaml
from box import Box


def argument_parsing():
    """ Parse arguments from command line
    :return Object of all arguments
    """
    parser = argparse.ArgumentParser(description="Load configuration file to environnement variable to use shell command")
    parser.add_argument('-r', '--repo', help='Repository name', required=True)
    parser.add_argument('-c', '--config', help='Configuration file (default: config.yml)', default="config.yml")
    parser.add_argument('restic_params', help="List of parameters for restic command", nargs='+')
    return parser.parse_known_args()


def load_config(filename: str) -> Box:
    with open(filename, 'r') as ymlfile:
        cfg = yaml.load(ymlfile, Loader=yaml.FullLoader)
    return Box(cfg, box_it_up=True)


if __name__ == '__main__':
    args, others = argument_parsing()
    config = load_config(args.config)

    restic_cmd = (
        f"{config.binaries.restic} "
        f"-r rclone:{config.information.rclone_connection_name}:{config.information.bucket_name}/"
        f"{config.information.client_name or ''}/{config.information.server_name or ''}/{args.repo}"
    )
    restic_cmd = re.sub(r'(/+){2}', '/', restic_cmd)

    params = ' '.join(args.restic_params)
    if others:
        params = f"{params} {' '.join(others)}"
    print(fr"==> {restic_cmd} {params}")
    subprocess.run(fr"{restic_cmd} {params}", shell=True)
